### ISSUE TITLE
Consecutive "wait-serial" commands sometimes fail matching

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-cli#13]
For example, in this scenario taken from [platform-io-esp32-http-client](https://github.com/wokwi/platform-io-esp32-http-client/blob/main/http-client.test.yaml):

```yaml
name: HTTP Client Test
version: 1
author: Uri Shaked

steps:
  - wait-serial: 'Connecting to WiFi'
  - wait-serial: 'Fetching http://example.org... HTTP 200'
  - wait-serial: '<title>Example Domain</title>'
```

The matching fails in cases when two expected lines are returned in a single buffer (e.g. both `Fetching http://example.org... HTTP 200` and `<title>Example Domain</title>` are returned in one buffer).
