### ISSUE TITLE
rp2040 (pico) bug in ADC, always read 0 in wokwi-cli

### ISSUE THREAD

**Issue by rafaelcorsi** [wokwi/wokwi-cli#14]
Hi! I noticed there might be an issue with the ADC functionality when using it via the CLI. To facilitate reproduction of the bug, I've created an example project available at:

- https://github.com/rafaelcorsi/wokwi-ci-bug-adc-rp2040

Description:

The project consists of a simple C program for the RP2040/Pico/PicoW that reads from the ADC and outputs the analog value to the UART/terminal. When simulating the circuit using the diagram simulation, everything works correctly. However, when executing the simulation through the Wokwi CLI with wokwi-cli --scenario test.yml, the ADC value is consistently reported as 0. 

I've also tested connecting the ADC port on PICO to the VCC, to check if the problem is with the potentiometer, and it gives the same value, so I think that the problem is on the pico side.

## Diagram works!

![image](https://github.com/wokwi/wokwi-cli/assets/1039615/2479a347-2da6-4cf7-a5f4-47dcc990a449)

## wokwi-cli erro

![image](https://github.com/wokwi/wokwi-cli/assets/1039615/77a41484-7e84-4fc4-ba8f-1a40f4667955)

**Comment by urish** [comment]
Thanks for reporting! I believe the issue here is that since we don't have the UI, the initial value for the potentiometer is 0, and is not read from the diagram.json. Looking into this.

**Comment by urish** [comment]
Quick workaround: setting the pot value immediately after the simulation starts, e.g.

```yaml
name: exe1
author: Rafael Corsi
version: 1

steps:
  - delay: 1ms
  - set-control:
      part-id: pot1
      control: position
      value: 0.5
  - delay: 300ms
  - wait-serial: 'adc 1: 2047'
```
