### ISSUE TITLE
Enable change potentiometer value from test.yml

### ISSUE THREAD

**Issue by rafaelcorsi** [wokwi/wokwi-cli#27]
Hello,

Can you please enable to change a potentiometer value from the `test.yml`?

I've set up a repo with an example:

- https://github.com/rafaelcorsi/wokwi-ci-pot

![Image](https://github.com/user-attachments/assets/15f31ff7-7fad-41f1-8a68-7b57181f3206)

``` yml
name: main
author: Rafael Corsi
version: 1

steps:
  - delay: 200ms

  - set-control:
      part-id: pot1
      control: value
      value: 0
  - delay: 100ms

  - set-control:
      part-id: pot1
      control: value
      value: 700
  - delay: 200ms

  - wait-serial: '2802'

  - set-control:
      part-id: pot1
      control: value
      value: 300
  - delay: 200ms

  - wait-serial: '1200'

```

result:

```
➜  main git:(main) ✗ wokwi-cli --scenario test.yaml
Wokwi CLI v0.16.0 (ff220a404971)
Connected to Wokwi Simulation API 1.0.0-20250422-gb7ed8877
Starting simulation...
[main] delay 200ms
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
[main] delay 100ms
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
[main] delay 200ms
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
```
