### ISSUE TITLE
Cryptic error message when "delay" value is a number

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-cli#3]
To reproduce:

```yaml
name: Example scenario
version: 1
author: Uri Shaked

steps:
  - delay: 1
```

This fails with a cryptic error message: 

```
C:\projects\wokwi-cli\src\utils\parseTime.ts:4
  time = time.trim();
              ^
TypeError: time.trim is not a function
    at parseTime (C:\projects\wokwi-cli\src\utils\parseTime.ts:4:15)
    at DelayCommand.run (C:\projects\wokwi-cli\src\scenario\DelayCommand.ts:12:28)
    at TestScenario.executeStep (C:\projects\wokwi-cli\src\TestScenario.ts:88:34)
    at TestScenario.start (C:\projects\wokwi-cli\src\TestScenario.ts:78:18)
    at main (C:\projects\wokwi-cli\src\main.ts:181:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
