### ISSUE TITLE
Ultrasonic Sensor not working correctly

### ISSUE THREAD

**Issue by kontiko** [wokwi/wokwi-cli#4]
I editted the example from https://github.com/wokwi/platform-io-esp32-counter-ci/ to integrate a Ultrasonic sensor. When running in the online editor or the vs code extention it works fine, but when running it via the cli the sensor only returns its max value
[platform-io-esp32-counter-ci.zip](https://github.com/wokwi/wokwi-cli/files/11959616/platform-io-esp32-counter-ci.zip)

**Comment by urish** [comment]
Hi, took a look at the files you posted - is this your attempt to control the distance through the CI automation scanerio?

```yaml
  - set-control:
      part-id: ultrasonic1
      control: distance
      value: 100
```
