### ISSUE TITLE
Difficulty in determining control names for components

### ISSUE THREAD

**Issue by rafaelcorsi** [wokwi/wokwi-cli#7]
I understand that this feature is still in beta, but I'd like to note that there currently seems to be no way to identify the control name for a given component. For instance, I'm trying to trigger the motion signal on the [PIR motion sensor](https://docs.wokwi.com/parts/wokwi-pir-motion-sensor) from a test scenario, but I haven't been successful. 

I've attempted several keywords such as `motion`, `pressed`, `emotion`, and `trigger`, but none have worked. It looks like that repository that implement this components is private, so no way to look at the source code. 

Example:

``` yml
  - set-control:
      part-id: pir1
      control: trigger
      value: 1

  - set-control:
      part-id: pir1
      control: trigger
      value: 0
```

all the best
